apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-app-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager # This must match your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: main-app-env-secret # The name of the K8s Secret created
    creationPolicy: Owner
  data:
    - secretKey: FROM_MAIN
      remoteRef:
        key: my-app/db-credentials # e.g., prod/main-app/env
        property: FROM_MAIN
    - secretKey: MICROSERVICE_URL
      remoteRef:
        key: my-app/db-credentials
        property: MICROSERVICE_URL