# Shared configuration
namespace: default

microservice:
  replicaCount: 2
  image:
    repository: "123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app-repo"
    tag: "latest"
    pullPolicy: IfNotPresent
  awsSecretName: "" # Overridden in env values

# ClusterSecretStore name installed in your EKS cluster
secretStoreName: aws-secretsmanager