namespace: prod

mainApp:
  replicaCount: 3
  image:
    repository: "123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app-repo"
    tag: "latest" # Default tag
    pullPolicy: IfNotPresent
  awsSecretName: "my-app/db-credentials" # Overridden in env values

# ClusterSecretStore name installed in your EKS cluster
secretStoreName: aws-secretsmanager
# Production-grade resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi